# Generated by Django 5.2.9 on 2026-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
