# Generated by Django 5.2.9 on 2026-01-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_role_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctorassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassignment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lab_reports', 'Lab Reports'), ('prescriptions', 'Prescriptions'), ('diagnoses', 'Diagnoses'), ('vitals', 'Vitals'), ('imaging', 'Imaging'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('attention', 'Needs Attention'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='api.profile')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='PatientDoctorAssignment',
        ),
    ]
