# Generated by Django 5.2.9 on 2026-01-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_medical_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='facility',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
